### ISSUE TITLE
[backend] Server does not validate if an "abgabe" does conform to the rules

### ISSUE THREAD

**Issue by stheid** [ApolloLV/flunkysimulator#12]
§9.3 Abs 1 of the UPB Flunkyteams rules state, that an Abgabe is only admissable if the team, conducting the abgabe, has at least touched the center with their throw.

Currently any player can finish, no rule check whatsoever

**Comment by ApolloLV** [comment]
We also have a closenohit event that should be considered as valid for Abgabe as well.

**Comment by moreApi** [comment]
Currently the server trys to enforce as less rules as possible. The server will likely not run perfect in the first trys and might go into wrong states. If we have in additon to a wonky server wonky rule execution we might lose player favor fast. Version 3 on the other hand should care about that.

**Comment by moreApi** [comment]
merged with #20
