### ISSUE TITLE
Users as lists of checkboxes and automatically select the next player

### ISSUE THREAD

**Issue by stheid** [ApolloLV/flunkysimulator#2]
if the checkbox, the user is done and should be skipped when it is his turn.

adding the checkboxes could be done with input boxes that add checkbox entries are added on enter event

**Comment by moreApi** [comment]
done by the backend

**Comment by stheid** [comment]
This issue was mainly meant for the UI maybe we can leave it open for now?

**Comment by ApolloLV** [comment]
Implemented this in the frontend as well.
