### ISSUE TITLE
[server] decrementing strafbiers can get negative

### ISSUE THREAD

**Issue by stheid** [ApolloLV/flunkysimulator#21]
decrementing a teams strafbier, when the team has no strafbier, will result in negative strafbier count

**Comment by ApolloLV** [comment]
This can't happen in the JS web client, since I display the decrement button only for positive numbers.

**Comment by stheid** [comment]
clear, but it can happen in general. And i think this is more a flaw of the webclient than a feature, because what happens if one presses accidently? or if there is a "strafbierausgleich" or a discussion yielding to removing a strafbier?

should be a minor task anyway
