### ISSUE TITLE
[webclient] reloading the page does not allow to reclaim player

### ISSUE THREAD

**Issue by stheid** [ApolloLV/flunkysimulator#24]
The player should be linked and relinked to the client.

The webclient should also allow to "Quit" effectively kicking itself.

in later versions some heartbeat and automatic disconnect could be an idea

**Comment by ApolloLV** [comment]
It is possible, you should actually be automatically reclaiming the player on reload. What did you observe?

**Comment by moreApi** [comment]
Maybe have a popup and ask the player to rejoin if there is already a name in the input field

**Comment by stheid** [comment]
i will have to recheck in the next rolled out version

**Comment by ApolloLV** [comment]
It used to be fixed, now it is broken again, but I should be able to fix it for the next version.

**Comment by stheid** [comment]
@ApolloLV is it fixed?

**Comment by stheid** [comment]
i am quite sure it is fixed except the player contains umlauts or other escaped stuff (#82, #93)

**Comment by ApolloLV** [comment]
Since I am just re-registering with the un-escaped raw client side form value, why would reclaiming not work?

**Comment by stheid** [comment]
because the raw one does not help. we need the escaped one from the server to match with the playernames from the gamestate (also from the server). As long as the server just returns the escaped username during registration, but not when re-registering, it is broken.

The unescaped raw string, is completely useless. Everything is using the data from the backend (gamestate)!

**Comment by ApolloLV** [comment]
What is the difference between registering and re-registering after a page reload? I thought the process was identical from the server perspective?

**Comment by ApolloLV** [comment]
Aaaah, I think I get your point. The username already being in use is the culprit, since the server will send a different response in this case. @moreApi shouldn't that be a trivial fix on the server side? Just send the escaped string in both cases?

**Comment by ApolloLV** [comment]
Ah, this is already fixed on developed. That means as soon as @moreApi deploys this (as requested in #101) reclaiming should also work for umlauts etc.

**Comment by ApolloLV** [comment]
Also the automatic rejoin with a popup has been implemented in #100
