### ISSUE TITLE
Username validation

### ISSUE THREAD

**Issue by stheid** [ApolloLV/flunkysimulator#26]
remove nonprintable characters and match users accoringly (names with trailing whitespaces for example)

**Comment by moreApi** [comment]
using google.rpc.status with any fields https://stackoverflow.com/questions/48748745/pattern-for-rich-error-handling-in-grpc/48750825#48750825 any field contains error response

**Comment by moreApi** [comment]
Not using rich error handling by google as desribed above because there is no grpc-web support
