### ISSUE TITLE
Server: Log name changes

### ISSUE THREAD

**Issue by ApolloLV** [ApolloLV/flunkysimulator#31]
If we extend the registerPlayerReq with the old player name, we might be able to thwart false-flag takeovers somewhat (at least where no second tab/browser is involved)

**Comment by moreApi** [comment]
I would prefere to solve this issue deeper eg. with #29 . Thinking about our first session those actors not stopped by having simply to open a new tab.

**Comment by ApolloLV** [comment]
I have implemented this with a client chat message in clientJS, but would still prefer a backend solution.
This also helps when more than one user is using the same tab and switches the user name

**Comment by moreApi** [comment]
This is/will be resolved in other issues right?
