### ISSUE TITLE
[serverKotlin] intoduce resting period after hit

### ISSUE THREAD

**Issue by ApolloLV** [ApolloLV/flunkysimulator#37]
We are currently delaying the new game state by the drinking time.
Add 2 seconds additional, hardcoded delay to account for processing times/lag.

**Comment by moreApi** [comment]
add restingPeriod flag to game state. If it it is set, lock throwing buttons. Resting period is active for a few seconds after a hit. -> shoud destress the game

**Comment by ApolloLV** [comment]
Maybe also add a short resting period even after a no-hit event

**Comment by JustMyGithub** [comment]
2 seconds is definitely not long enough
