### ISSUE TITLE
[Server] Incorrect next throwing player in log

### ISSUE THREAD

**Issue by ApolloLV** [ApolloLV/flunkysimulator#38]
The log contains text like this:

> Johanna hat normal geworfen
> Johanna hat nicht für Team Rechts getroffen.
> Johanna ist der/die nächste Wefer.

**Comment by ApolloLV** [comment]
As a side note, there is typo in Werfer.
I suggest to put it as "Johanna ist mit Werfen dran" instead, avoiding the awkward der/die.

**Comment by stheid** [comment]
The typo is already fixed, but i agree that the new formulation woul be better 75fc700fed85f56439c04106bbecd4a4d4189089
