### ISSUE TITLE
hold last frame of throwing video until start of stop video

### ISSUE THREAD

**Issue by stheid** [ApolloLV/flunkysimulator#4]
currently: after the throwing video the page is blank, but holding the last frame would be much more intuitive

**Comment by stheid** [comment]
@moreApi  Why is this for version n+1? think this is a quite important feature as it causes a lot of confusion with strong hits.

**Comment by ApolloLV** [comment]
This is non-trivial, unfortunately

**Comment by stheid** [comment]
must be conditional handling in https://github.com/ApolloLV/flunkysimulator/blob/develop/client/public/js/client.js#L79-L81

**Comment by moreApi** [comment]
can we do that in version 2.2? I would like to close 2.1 and only add fixes there.

**Comment by stheid** [comment]
it is done, just needs to be verified. thats why i added it to the milestone
