### ISSUE TITLE
Tell players what is new in this version

### ISSUE THREAD

**Issue by moreApi** [ApolloLV/flunkysimulator#45]
via popup or message of the day in chat

via client or server?

**Comment by JustMyGithub** [comment]
What about telling the players which version they use in the first place?

**Comment by moreApi** [comment]
Everybody uses the newest version by default and we dont have real versions numbers anyway.

**Comment by ApolloLV** [comment]
I think this should be in the log stream by the server.

**Comment by moreApi** [comment]
done
