### ISSUE TITLE
Sync player highlighting (blue) with video playback

### ISSUE THREAD

**Issue by JustMyGithub** [ApolloLV/flunkysimulator#53]
The player changes no matter what the status of the video download is. This causes the highlighted player happens to change before the bottle is even hit and the users get confused whether its their turn to drink or the opponents'.

**Comment by ApolloLV** [comment]
We decided to address this with the cool down period mentioned in #37, which should work as long as there is no reeeally big lag of several seconds.

**Comment by JustMyGithub** [comment]
Will the change of the highlighted player be delayed as well?

**Comment by ApolloLV** [comment]
Yes, you get the new game state with a new throwing player only after the resting period.
