### ISSUE TITLE
If a player causes a Strafbier don't call it "Abgabe abgenommen"

### ISSUE THREAD

**Issue by JustMyGithub** [ApolloLV/flunkysimulator#58]

**Comment by stheid** [comment]
Currently, this button is not ment to be clicked when starting an abgabe, but to accept a succesfull abgabe. To properly validate abgabe with respect to the rules a lot of protocol changes would need to be done #12

**Comment by moreApi** [comment]
I don't understand the issue. We have already two issues concerning abgabe and if I understand stheid this issue is covered by them.
