### ISSUE TITLE
Confirm when kicking people by popup

### ISSUE THREAD

**Issue by moreApi** [ApolloLV/flunkysimulator#61]
one click to kick is dangerous

**Comment by ApolloLV** [comment]
We can implement the same confirm dialog as in #43

**Comment by stheid** [comment]
textproposal:

    Du willst <Playername> rauswerfen
    [ <playername> rauswerfen ] [ abbrechen]

https://getbootstrap.com/docs/4.0/components/modal/

**Comment by stheid** [comment]
quickfix with javascript confirm(). i think for later versions i would do those dialogs with modals but its not as trivial as i thought initially
