### ISSUE TITLE
Ideas to store the videos

### ISSUE THREAD

**Issue by stheid** [ApolloLV/flunkysimulator#9]
### Problem
videos at heroku

### Solution idea
Store videos in a fileserver (sciebo, Dropbox)
Backend server passes a secret to the client
JS clients get the secret and the urls where the videos are store.

**Comment by ApolloLV** [comment]
I think the proper solution would be something like Amazon E3. I will have to figure out how to handle configuration secrets in heroku.

**Comment by ApolloLV** [comment]
One issue with Amazon S3 is that it does not support serving files via TLS. You'd have to setup another intermediate layer of cloudfront. 
An advantage is the cheap usage-based cost, and for the first 12 months, it should be free entirely, if we don't exceed the generous quota limits.

**Comment by stheid** [comment]
My server should be powerful enough to serve the videos. i have 40TB Quota a month. FTP...

if the kotlin server serves the download urls they can be cryptic urls (perhaps hashes of filenames such that they can be renamed on the server accordingly). I assume that is sufficiently secure.

**Comment by sessfeld** [comment]
From my experience with gCloud, you have 5gb free, and can serve TLS with signed URLs that expire after a certain amount of time.

**Comment by stheid** [comment]
videos are now hosted via sciebo
